config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :user_shoes
  resources :brands
  resources :shoe_stores
  resources :shoes
  resources :stores
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'\

  delete '/shoes/:id/remove', to: 'shoes#remove', as: 'remove_shoe'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :shoes
end

app/models/shoe.rb
class Shoe < ApplicationRecord
  has_many :shoe_stores
  has_many :stores, through: :shoe_stores
  belongs_to :brand
  has_many :user_shoes
  has_many :users, through: :user_shoes

  # def get_name
  #   self.name.split(" -").first
  # end


end

app/models/shoe_store.rb
class ShoeStore < ApplicationRecord
  belongs_to :store
  belongs_to :shoe
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :shoe_stores
  has_many :shoes, through: :shoe_stores
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_shoes
  has_many :shoes, through: :user_shoes

  has_secure_password
  validates :username, presence: true, uniqueness: true

end

app/models/user_shoe.rb
class UserShoe < ApplicationRecord
  belongs_to :shoe
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user

    def current_user
        if @current_user
            @current_user
        else
            @current_user = User.find_by(id: session[:user_id])
        end
    end

    def home
      
    end

end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

  def index
    @brands = Brand.all
  end

  def show
    @brand = Brand.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    # byebug
    if current_user
      redirect_to user_path(current_user)
    else
      render :new
    end

  end

  def create
    @user = User.find_by(username: params['username'])

    if !@user.nil?
        session[:user_id] = @user.id
        redirect_to user_path(@user)
    else
        redirect_to new_user_path
    end
  end

  def destroy
    session.clear
    redirect_to users_path
  end
end

app/controllers/shoe_stores_controller.rb
class ShoeStoresController < ApplicationController
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController

  def index
    @shoes = Shoe.all
    @sizes = Shoe.pluck(:size).uniq
  end

  def show
    @shoe = Shoe.find(params[:id])
  end

  def remove
    @shoe = Shoe.find(params[:id])
    current_user.shoes.delete(@shoe)
    redirect_to user_path(current_user)
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

  def index
    @stores = Store.all
  end

  def show
    @store = Store.find(params[:id])
  end




end

app/controllers/user_shoes_controller.rb
class UserShoesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  # def create
  #     @user = User.new(user_params)
  #   if @user.valid?
  #     @user.save
  #     session[:user_id] = @user.id
  #     redirect_to user_path(@user)
  #   else
  #     flash[:error] = @user.errors.full_messages
  #     redirect_to new_user_path
  #   end
  # end
  def create
    @user = User.new()
    @user.attributes = user_params
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:error] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def update
    current_user.shoes << Shoe.find(params[:shoe_id])

    redirect_to user_path(current_user)
  end

  def destroy

  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shoe_stores_helper.rb
module ShoeStoresHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/user_shoes_helper.rb
module UserShoesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/brands/index.html.erb
<h1> Brands List </h1>

<ul>
  <% @brands.each do |brand| %>
    <li><%= link_to brand.name, brand_path(brand) %></li>
  <% end %>
</ul>

app/views/brands/show.html.erb
<%= @brand.name %>
<ul>
<% @brand.shoes.each do |shoe| %>
  <li><%= link_to shoe.name, shoe_path(shoe) %></li>
<% end %>
</ul>

app/views/shoes/index.html.erb
<h1>Shoe List</h1>
<br></br>
<select name="size-filter" >
  <% @sizes.each do |size| %>
<option value= <%= size %> ><%= "Size #{size}" %> </option>
<% end %>
</select>
<br>
<br><%= link_to "My Dashboard", user_path(current_user) %></br>
<br></br>
</div>
<ul>
  <% @shoes.each do |shoe| %>
    <li><%= link_to shoe.name, shoe_path(shoe) %></li>
    <br>
  <% end %>
</ul>

app/views/shoes/show.html.erb
<h3><%= @shoe.name %></h3>

<% if current_user.shoes.include?(@shoe) %>
  <%= button_to("Remove From Watchlist", remove_shoe_path, :method => :delete, params: {shoe_id: @shoe.id}) %>
<% else %>
  <%= button_to("Add To Watchlist", user_path(current_user), :method => :patch, params: {shoe_id: @shoe.id}) %>
<% end %>
<img src=<%= @shoe.image_url %> height="300">
<h4>Price: $<%= @shoe.price %></h4>
<h4>Tech: <%= @shoe.tech %></h4>
<h4>Size: <%= @shoe.size %></h4>
<ul>
  <% @shoe.shoe_stores.each do |shoe_store| %>
    <li><%= link_to shoe_store.store.name, store_path(shoe_store.store) %>
     <%= "- #{shoe_store.quantity} in stock" %></li>
  <% end %>
</ul>

app/views/stores/index.html.erb
<h1> Store List </h1>

<ul>
<% @stores.each do |store| %>
  <li><%= link_to store.name, store_path(store) %></li>
<% end %>
</ul>

app/views/stores/show.html.erb
<h3><%= @store.name %></h3>
<h4>City:</h4> <h5><%= @store.city %></h5>
<h4> Shoes </h4>
<ul>
<% @store.shoes.each do |shoe| %>
  <li><%= link_to shoe.name, shoe_path(shoe) %></li>
<% end %>
</ul>

app/views/users/index.html.erb
<h1 align="center">Welcome To ShoeStack</h1>
<body>
<div align="right" style="vertical-align: top;"><%= link_to "Login",  login_path %></div><br>
<div align="right" style="vertical-align: top;"><%= link_to "Create Account",  new_user_path %></div>

<img src="https://i.imgur.com/hBLgg35.jpg" style="float: left; width: 28%; margin-left: 2.5%; margin-right: 2.5%; margin-bottom: 0.5em;">
<img src="https://www.flightclub.com/media/catalog/product/cache/1/image/1600x1140/9df78eab33525d08d6e5fb8d27136e95/8/0/800283_1.jpg" style="float: left; width: 28%; margin-left: 2%; margin-right: 2%; margin-bottom: 0.5em;">
<img src="https://i.imgur.com/OZYQBcb.jpg" style="float: left; width: 28%; margin-left: 2.5%; margin-right: 2.5%; margin-bottom: 0.5em;">
<img src="https://www.flightclub.com/media/catalog/product/cache/1/image/1600x1140/9df78eab33525d08d6e5fb8d27136e95/8/0/801781_01.jpg " style="float: left; width: 28%; margin-left: 2.5%; margin-right: 2.5%; margin-bottom: 0.5em;">
<img src="https://www.flightclub.com/media/catalog/product/cache/1/image/1600x1140/9df78eab33525d08d6e5fb8d27136e95/8/0/801820_1_2.jpg" style="float: left; width: 28%; margin-left: 2.5%; margin-right: 2.5%; margin-bottom: 0.5em;">
<img src="https://www.flightclub.com/media/catalog/product/cache/1/image/1600x1140/9df78eab33525d08d6e5fb8d27136e95/8/0/802783_01.jpg" style="float: left; width: 28%; margin-left: 2.5%; margin-right: 2.5%; margin-bottom: 0.5em;">
<img src="https://www.flightclub.com/media/catalog/product/cache/1/image/1600x1140/9df78eab33525d08d6e5fb8d27136e95/8/0/803537_2.jpg" style="float: left; width: 28%; margin-left: 2.5%; margin-right: 2.5%; margin-bottom: 0.5em;">
<img src="https://www.flightclub.com/media/catalog/product/cache/1/image/1600x1140/9df78eab33525d08d6e5fb8d27136e95/8/0/801894_1.jpg" style="float: left; width: 28%; margin-left: 2%; margin-right: 2%; margin-bottom: 0.5em;">
<img src="https://i.imgur.com/EvjtDhO.jpg" style="float: left; width: 28%; margin-left: 2%; margin-right: 2%; margin-bottom: 0.5em;">







<p style="clear: both;">

</body>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Create New User</title>
</head>
<body>

<h1>Create New User</h1>

<ul>
    <% if flash[:error] %>
        <% flash[:error].each do |error| %>
            <li class="error"><%= error %></li>
        <% end %>
    <% end %>
</ul>

<%= link_to "Login", "/login" %>

<%= form_for(@user) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <%= f.label :username %>
    <%= f.text_field :username %><br>
    <%= f.label :password %>
    <%= f.password_field :password %><br>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %><br>
    <%= f.submit %>
<% end %>
</body>
</html>

app/views/users/show.html.erb
<h1><%= "#{current_user.username.capitalize if current_user}'s Dashboard" %><h1>
  <body>


<h2>Shoe Watchlist</h2></br>
<ul>
  <% if !current_user.shoes.empty? %>
    <% current_user.shoes.each do |shoe| %>
    <li><%= link_to "#{shoe.name}", shoe_path(shoe) %>
      <%= "| Price: $#{shoe.price}" %></li>
  <% end %>
<% end%>
</ul>

<br><%= link_to "Shoes", shoes_path %></br>
<br><%= link_to "Log out", logout_path, method: :delete %></br>
</body>